### ISSUE TITLE
it doesn't work in FreeMarker VERSION_2_3_31

### ISSUE THREAD

**Issue by TonyLuo** [lazee/freemarker-java-8#32] opened 2021-03-28 17:54 UTC
``` 
cfg = new Configuration(Configuration.VERSION_2_3_31);       
 cfg.setObjectWrapper(new Java8ObjectWrapper(Configuration.VERSION_2_3_31));

Instant arriveTime =  Instant.now();

 ${arriveTime.format('yyyy-MM-dd HH : mm : ss')}
```
the output is not printed as excepted: 2021-03-16T16:17:45Z

**Comment by lazee** [comment] 2021-03-29 10:21
Thanks for letting me now. It is not an uncommon thing that Freemarker are breaking stuff after a release, and there are no Release note (that I can find) that tells me what they have changed.

I will look into it.

**Comment by lazee** [comment] 2022-06-06 22:14
The problem isn't 2_3_31, but rather that I had not implemented a formatter for Clock and Instant. This will be fixed in the new version coming out in a short time. See https://github.com/lazee/freemarker-java-8/pull/36

**Comment by lazee** [comment] 2022-06-06 22:52
Closing issue as new release is around the corner.

**Closed as completed by lazee** 2022-06-06 22:52 UTC
Labels: bug, enhancement
